### ISSUE TITLE
Cannot build on OSX Lion 10.7.1

### ISSUE THREAD

**Issue by emoret** [zonque/PulseAudioOSX#2]
Hi I am running OSX Lion 10.7.1 with mac ports 2.0.3 and all ports described on the installation page installed with their universal variants. Here is the error message I get:

tests/once-test.c:39: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘barrier’
tests/once-test.c: In function ‘thread_func’:
tests/once-test.c:66: warning: implicit declaration of function ‘pthread_barrier_wait’
tests/once-test.c:66: error: ‘barrier’ undeclared (first use in this function)
tests/once-test.c:66: error: (Each undeclared identifier is reported only once
tests/once-test.c:66: error: for each function it appears in.)
tests/once-test.c:67: error: ‘PTHREAD_BARRIER_SERIAL_THREAD’ undeclared (first use in this function)
tests/once-test.c: In function ‘main’:
tests/once-test.c:82: warning: implicit declaration of function ‘pthread_barrier_init’
tests/once-test.c:82: error: ‘barrier’ undeclared (first use in this function)
tests/once-test.c:106: warning: implicit declaration of function ‘pthread_barrier_destroy’
tests/once-test.c:39: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘barrier’
tests/once-test.c: In function ‘thread_func’:
tests/once-test.c:66: warning: implicit declaration of function ‘pthread_barrier_wait’
tests/once-test.c:66: error: ‘barrier’ undeclared (first use in this function)
tests/once-test.c:66: error: (Each undeclared identifier is reported only once
tests/once-test.c:66: error: for each function it appears in.)
tests/once-test.c:67: error: ‘PTHREAD_BARRIER_SERIAL_THREAD’ undeclared (first use in this function)
tests/once-test.c: In function ‘main’:
tests/once-test.c:82: warning: implicit declaration of function ‘pthread_barrier_init’
tests/once-test.c:82: error: ‘barrier’ undeclared (first use in this function)
tests/once-test.c:106: warning: implicit declaration of function ‘pthread_barrier_destroy’
lipo: can't open input file: /var/folders/n8/p84dp74x6vjbg240qt9hc5hh0000gn/T//ccNgDKZi.out (No such file or directory)
make[3]: **\* [once_test-once-test.o] Error 1
make[2]: **\* [install] Error 2
make[1]: **\* [install-recursive] Error 1
make: **\* [install] Error 2

**Comment by zonque** [comment]
Coincidentally, I just fixed this bug and submitted a fix to the PulseAudio mailing list. Check today's archive. Basically it's just about removing the once-test executable from the list of build targets.

**Comment by emoret** [comment]
Could you update your instructions page with the proper git repo? I am unable to find the checkin matching your above mentioned contribution.

**Comment by zonque** [comment]
It's commit mainline - Just clone the tree from http://cgit.freedesktop.org/pulseaudio/pulseaudio/
